### ISSUE TITLE
Creating a release ?

### ISSUE THREAD

**Issue by pikulsky** [christoph-kluge/reactphp-http-cors-middleware#4]
Hi,
What about creating a release?
I'm asking since when I run "composer require christoph-kluge/reactphp-http-cors-middleware", I got an error:
```
  [InvalidArgumentException]
  Could not find a matching version of package christoph-kluge/reactphp-http-cors-middleware. 
Check the package spelling, your version constraint and that the package is available in a stability 
which matches your minimum-stability (stable).
```
The reason is my composer.json have no "minimum-stability" option, so it's "stable" by default.
Then, since the repo has no release, so  it defaults to "dev-master", so composer can't match.

A workaround is setting in composer.json:
```
    "minimum-stability": "dev",
    "prefer-stable": true
```
but I think it's not good to have "dev" as a "minimum-stability"..

**Comment by WyriHaximus** [comment]
+1

**Comment by christoph-kluge** [comment]
Hi @pikulsky, thank you for pointing this out. 

I will take a closer look today on the middleware. As far as I remember there was something missing in my opinion to make the module complete. Anyway I will check it and would add at least a 0.1.0 version to it. With this you should be able to use it w/o changing your minimum-stability.

**Comment by pikulsky** [comment]
> As far as I remember there was something missing in my opinion to make the module complete.

feel free to share with us

**Comment by christoph-kluge** [comment]
Sadly I will need some minutes to get back into the middleware but after a quick look into my local working state [here (8bc1f8d9fb)](https://github.com/christoph-kluge/reactphp-http-cors-middleware/commit/8bc1f8d9fba023b6997381de7845c8f2ce5fc46f) - I think that the problem was something with the server hostname if you don't define custom origins (as it's also is hardcoded right now)

I will try to clean it up during the day and then create a separate issue for the missing `getServerOrigin()` feature and make a release for the current version (after the cleanup).

Does it help you @pikulsky ?

**Comment by christoph-kluge** [comment]
I did a separate issue #5 for the mentioned topic above. In my opinion this missing feature should not block the initial release and will perfectly fit in a BC compatible minor version release.

**Comment by christoph-kluge** [comment]
@pikulsky initial middleware release was done. The first version [1.0.0](https://github.com/christoph-kluge/reactphp-http-cors-middleware/releases/tag/1.0.0) is out. 🎉 🎉 Going to close this issue.

**Comment by WyriHaximus** [comment]
@christoph-kluge awesome, thank you :tada:

**Comment by pikulsky** [comment]
@christoph-kluge great! thanks!
